INSERT INTO public.tb_user (display_name, password, username) VALUES('Fernando Loff', '$2a$10$WVs9in/pFr8eZc8Iz8TJc.OU9Gwhz9KVxskpUp7qW5GmVJzB51p8i', 'fernando');

INSERT INTO public.tb_category (name) VALUES('Montanha');
INSERT INTO public.tb_category (name) VALUES('Urbana');

INSERT INTO public.tb_product (price, category_id, name, description, url_img) VALUES(799, 2, 'KRW KR1', 'A bicicleta KRW KR1 foi desenvolvida para quem quer realizar um passeio e pegar trilhas leves. Com seu quadro em alumínio 6061, fornece segurança e leveza no seu pedal. Possuí diversas cores que garante um estilo próprio para você.', 'https://static.netshoes.com.br/produtos/bicicleta-aro-29-krw-aluminio-24-velocidades-freio-a-disco-suspensao-dianteira-mountain-bike-kr1/28/R3O-0015-028/R3O-0015-028_zoom1.jpg?ts=1715177619?ims=1088x');
INSERT INTO public.tb_product (price, category_id, name, description, url_img) VALUES(799, 1, 'KRW KR1', 'A bicicleta KRW KR1 foi desenvolvida para quem quer realizar um passeio e pegar trilhas leves. Com seu quadro em alumínio 6061, fornece segurança e leveza no seu pedal. Possuí diversas cores que garante um estilo próprio para você.', 'https://static.netshoes.com.br/produtos/bicicleta-aro-29-krw-aluminio-24-velocidades-freio-a-disco-suspensao-dianteira-mountain-bike-kr1/28/R3O-0015-028/R3O-0015-028_zoom1.jpg?ts=1715177619?ims=1088x');
INSERT INTO public.tb_product (price, category_id, name, description, url_img) VALUES(799, 2, 'KRW KR1', 'A bicicleta KRW KR1 foi desenvolvida para quem quer realizar um passeio e pegar trilhas leves. Com seu quadro em alumínio 6061, fornece segurança e leveza no seu pedal. Possuí diversas cores que garante um estilo próprio para você.', 'https://static.netshoes.com.br/produtos/bicicleta-aro-29-krw-aluminio-24-velocidades-freio-a-disco-suspensao-dianteira-mountain-bike-kr1/28/R3O-0015-028/R3O-0015-028_zoom1.jpg?ts=1715177619?ims=1088x');
INSERT INTO public.tb_product (price, category_id, name, description, url_img) VALUES(799, 1, 'KRW KR1', 'A bicicleta KRW KR1 foi desenvolvida para quem quer realizar um passeio e pegar trilhas leves. Com seu quadro em alumínio 6061, fornece segurança e leveza no seu pedal. Possuí diversas cores que garante um estilo próprio para você.', 'https://static.netshoes.com.br/produtos/bicicleta-aro-29-krw-aluminio-24-velocidades-freio-a-disco-suspensao-dianteira-mountain-bike-kr1/28/R3O-0015-028/R3O-0015-028_zoom1.jpg?ts=1715177619?ims=1088x');
